# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

target 'TodayNBANews' do
    pod 'Masonry'
    pod 'CocoaLumberjack'
end

target 'TodayNBANewsTests' do

end

